services:
  dbticketservice:
    image: "randomnoob13/dbservice:v1"
    container_name: dbticketservice
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - "armanair"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - db_ticket_data:/var/lib/mysql

  ticketservice:
    image: "randomnoob13/ticketservice:v1"
    container_name: ticketservice
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - "armanair"
    depends_on:
      dbticketservice:        # Dies sollte dbticketservice sein, nicht dbservice
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://dbticketservice:3306/webtechproject"  # Auch hier den Namen anpassen
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "RootTestPassword"

  dbflightsservice:
    image: "randomnoob13/dbflightsservice:v1"
    container_name: dbflightsservice
    ports:
      - "3307:3306"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - "armanair"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - db_flights_data:/var/lib/mysql

networks:
  "armanair":
    driver: "bridge"

volumes:
  db_ticket_data:    # Separates Volume für Ticket-Datenbank
  db_flights_data:   # Separates Volume für Flights-Datenbank