services:
  dbservice:
    image: "mysql:latest"
    container_name: dbservice
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - "backend-network"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "TestPassword"
      MYSQL_DATABASE: "database"

  usermanagementservice:
    image: "randomnoob13/usermanagementservice:v1-development-environment"
    container_name: usermanagementservice
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - "backend-network"
    depends_on:
      dbservice:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://dbservice:3306/database"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "TestPassword"


  autocompleteservice:
    image: "randomnoob13/autocomplete:v3"
    container_name: autocompleteservice
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - "backend-network"




networks:
  backend-network:
    driver: bridge

volumes:
  db_data:
    driver: local