 spring:
    application:
      name: "armanAirlines"
    config:
      activate:
        on-profile: "test"
      import: "optional:file:.env[.yml]"

    datasource:
      url: "${SPRING_DATASOURCE_URL}"
      username: "${SPRING_DATASOURCE_USERNAME}"
      password: "${SPRING_DATASOURCE_PASSWORD}"



