FROM mysql:latest

# Setzt Umgebungsvariablen für die DB
ENV MYSQL_ROOT_PASSWORD=RootTestPassword
ENV MYSQL_DATABASE=webtechproject
ENV MYSQL_USER=TestUser
ENV MYSQL_PASSWORD=TestPasswort

# Kopiert die schema.sql Datei in das Docker Verzeichnis und führt Schema.sql aus
COPY */schema.sql /docker-entrypoint-initdb.d/

