FROM openjdk:20-slim

# Create app directory
WORKDIR /app

# Copy the application's jar to the container
COPY target/TicketService-0.0.1-SNAPSHOT.jar ./TicketService.jar

# Execute the application
ENTRYPOINT ["java", "-jar", "TicketService.jar"]