
spring:
  application:
    name: "FlightsService"

  datasource:
    url: "${SPRING_DATASOURCE_URL}"
    username: "${SPRING_DATASOURCE_USERNAME}"
    password: "${SPRING_DATASOURCE_PASSWORD}"

  config:
    import: "optional:file:.env[.yml]"
