## BUILD Stage ##
FROM maven:3.9.9-eclipse-temurin-21-alpine AS build

WORKDIR /app

# Kopieren der Projektdateien
COPY pom.xml .
COPY src ./src

# Maven Build ohne Datenbank-Konfiguration
RUN mvn clean package -DskipTests

## Package Stage ##
FROM eclipse-temurin:21-jdk-jammy

# Deklaration der Environment Variablen
ENV SPRING_DATASOURCE_PASSWORD=""
ENV SPRING_DATASOURCE_URL=""
ENV SPRING_DATASOURCE_USERNAME=""

COPY --from=build /app/target/UserManagementService-0.0.1-SNAPSHOT.jar app.jar

ENTRYPOINT ["java", "-jar", "/app.jar"]