 spring:
    application:
      name: "armanAirlines"
    config:
      activate:
        on-profile: "test"
    datasource:
      url: "jdbc:mysql://localhost:3306/webtechproject"
      username: "root"
      password: "RootTestPassword"
    sql:
      init:
        mode: always